export class Onscreen {
    onscreen_id: number;
	title: string;
	type: string;
	status: string;
	imdb_id: string;
	year: string;
	released: string;
	rated: string;
	runtime: number;
	seasons: number;
	episodes: number;
	genres: string;
	poster: string;
	directors: string;
	writers: string;
	production: string;
	network: string;
	imdb_rating: number;
	imdb_votes: number;
	rotten_tomatoes: number;
	metascore: number;
	language: string;
	country: string;
	budget: number
	trailer: string;
	books: Array<any>
	shorts: Array<any>
}
